### ISSUE TITLE
MBBS notes providing website landing page

### ISSUE THREAD

**Issue by priyanshi1282** [praveenscience/Creative-Simple-Landing-Pages#78]
Hey @praveenscience , I want to add landing page which is responsive.
preview : 
https://priyanshi1282.github.io/MedEasy-MBBS-Notes-Providing-Website/
pls consider this under hacktober22.

**Comment by praveenscience** [comment]
Interesting. Just one question. Have you done it yourself without any plagiarism? 👏🏻 If so, yes, please feel free to raise a PR.

**Comment by priyanshi1282** [comment]
> Interesting. Just one question. Have you done it yourself without any plagiarism? 👏🏻 If so, yes, please feel free to raise a PR.

Yes ofc, I have developed this by myself :)
