### ISSUE TITLE
Online Shopping Website

### ISSUE THREAD

**Issue by priyanshi1282** [praveenscience/Creative-Simple-Landing-Pages#88]
Hey @praveenscience , I want to add a template for online shopping, which is responsive.
Tech stack used : html, css and bootstrap.
here is the preview : https://priyanshi1282.github.io/online-shopping-website/
pls consider this under hacktober22.

**Comment by praveenscience** [comment]
Hey go ahead and do it please. In this repo, you don't need to create issues. 😊

**Comment by praveenscience** [comment]
Done in #93... 💪🏻😁
